"""empty message

Revision ID: 1519e1d62ab3
Revises: 69866dad2b84
Create Date: 2022-05-02 19:02:52.187915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1519e1d62ab3'
down_revision = '69866dad2b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('favorite_ibfk_4', 'favorite', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('favorite_ibfk_4', 'favorite', 'vehicle', ['favorite_vehicle'], ['id'])
    # ### end Alembic commands ###
