"""empty message

Revision ID: 69866dad2b84
Revises: 8841b49b3a4d
Create Date: 2022-05-02 13:21:29.800806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69866dad2b84'
down_revision = '8841b49b3a4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['email'])
    op.create_unique_constraint(None, 'user', ['userName'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
