"""empty message

Revision ID: 7cae6e35e4a6
Revises: ae8a197d8a5f
Create Date: 2022-04-29 07:55:58.654150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cae6e35e4a6'
down_revision = 'ae8a197d8a5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('planet', sa.Column('edited', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planet', 'edited')
    op.drop_column('planet', 'created')
    # ### end Alembic commands ###
