"""empty message

Revision ID: 8baed4a3d60d
Revises: 8cc217d6927b
Create Date: 2022-04-28 19:24:26.194363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8baed4a3d60d'
down_revision = '8cc217d6927b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character', 'created')
    # ### end Alembic commands ###
