"""empty message

Revision ID: bb94b0d1515c
Revises: 2e331adc9820
Create Date: 2022-04-29 07:58:18.620354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb94b0d1515c'
down_revision = '2e331adc9820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('vehicle', sa.Column('edited', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle', 'edited')
    op.drop_column('vehicle', 'created')
    # ### end Alembic commands ###
